server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: notification-service

  profiles:
    active: dev

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/notificationdb}
    username: ${DATABASE_USERNAME:notificationuser}
    password: ${DATABASE_PASSWORD:notificationpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.saga: DEBUG